site_name: Pareto
site_url: https://alandefreitas.github.io/pareto/
repo_url: https://github.com/alandefreitas/pareto
repo_name: alandefreitas/pareto

site_description: Spatial Containers, Pareto Fronts and Pareto Archives

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: preference
  icon:
    repo: fontawesome/brands/git-alt
    logo: fontawesome/solid/code

edit_uri: ""

plugins:
  - search
  - awesome-pages

google_analytics:
  - UA-109858331-4
  - auto

copyright: Copyright &copy; 2020 Alan Freitas

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - meta

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://media.ethicalads.io/media/client/ethicalads.min.js