name: ParetoFront

on: [ push, pull_request ]

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows/Static/X64/Release",
            os: windows-latest,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64, # the github machine cannot build the python bindings
          }
          - {
            name: "Linux/Static/X64/Release",
            os: ubuntu-latest,
            config: Release,
            args: "-DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8",
          }
          - {
            name: "MacOSX/Static/X64/Release",
            os: macos-latest,
            config: Release,
            args: "",
          }
    steps:
      - uses: actions/checkout@v2
#      - name: Install python3-dev on Linux
#          if: matrix.config.os == 'ubuntu-latest'
#          run: |
#            sudo apt upgrade python3-dev
      - name: Create Work Dir
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: |
          cmake .. ${{ matrix.config.args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -DBUILD_LONG_TESTS=OFF -DMAX_NUM_DIMENSIONS_PYTHON=3 -DBUILD_BINDING_FOR_ALL_STRUCTURES=OFF
      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config ${{ matrix.config.config }}
      - name: Test
        working-directory: ./build
        run: ctest -j 2
