name: Contributions

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'
      - '!.github/workflows/contributors.yml'
      - 'documentation/**'
      - '.clang-format'
      - '.gitignore'
      - 'LICENSE'

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Contributions
    steps:
      - name: Update Contribution List
        uses: akhilmhdh/contributors-readme-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image_size: 100
          columns_per_row: 6

